export const FETCH_PRODUCT_REQUEST = 'MAIN/FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'MAIN/FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'MAIN/FETCH_PRODUCT_FAILURE';
